#make file

my_server:
	g++ -std=c++17 handling_files.cpp handling_input.cpp server_main.cpp -o my_server -lpthread

my_client:
	g++ -std=c++17 handling_files.cpp handling_input.cpp client_main.cpp -o my_client
